CODE_DESCRIPTORS = {
    "B1720": "Amount of balancing reserves under contract",
    "B1730": "Prices of procured balancing reserves",
    "B1740": "Accepted aggregated offers",
    "B1750": "Activated balancing energy",
    "B1760": "Prices of activated balancing energy",
    "B1770": "Imbalance prices",
    "B1780": "Aggregated imbalance volumes",
    "B1810": ("CrossBorder balancing volumes of exchanged bids" " and offers"),
    "B1820": "CrossBorder balancing prices",
    "B1830": "CrossBorder balancing energy activated",
    "B0610": "Actual total load per bidding zone",
    "B0620": "Day ahead total load forecast per bidding zone",
    "B1430": "Day ahead aggregated generation",
    "B1440": "Generation forecasts for wind and solar",
    "B1610": "Actual generation output per generation unit",
    "B1620": "Actual aggregated generation perType",
    "B1630": ("Actual or estimated wind and solar power" " generation"),
    "B1320": "Congestion management measure counter-trading",
}
