name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  docker:
    # only run if the tests passed
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          # build for x86 and arm
          # not supporting arm for now as it takes a long time to build
          # and since the other docker images can't build for arm, there's not point
          platforms: linux/amd64 #,linux/armv7
          push: true
          tags: dustpancake/aimlac-cc-models:latest