name: Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.py'
      - 'setup.cfg'

jobs:
  pytest:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    - name: Run unit tests
      run: |
        LOCATION_LAT=52.1051 LOCATION_LON=-3.6680 pytest -vvv .
    - name: Generate coverage report
      run: |
        echo "Test Coverage Report Summary:" > cov.txt
        echo "\`\`\`" >> cov.txt
        echo "Name                     Stmts   Miss  Cover" >> cov.txt
        echo "--------------------------------------------" >> cov.txt
        LOCATION_LAT=52.1051 LOCATION_LON=-3.6680 pytest --cov=src . | grep TOTAL >> cov.txt
        echo "\`\`\`" >> cov.txt
    - name: Comment coverage
      uses: machine-learning-apps/pr-comment@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: cov.txt